### ISSUE TITLE
Interpretting WCS Time as Datetime

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#112]
WCS handles time as seconds since an epoch.  This epoch is typically defined somewhere in the meta data.  Users are certainly going to want to view and index by time in date/time format as well as seconds since epoch.  The question is then, how can we provide that functionality?  Currently this can be done by adding date/time formatted time as an extra coordinate.  This seems very repetitious and not ideal for RAM considerations.  Is there a better way?

Ideas
* Perhaps a property ```WCS_time_to_datetime``` property can be added that takes an ```epoch``` arg and returns an array of datetime objects derived from the WCS time?  This would have to check if a time WCS axis exists before executing and would thus mean that in some cases, the method would not be useable.
* Have a ```base_time``` kwarg in ```pixel_to_world```, ```world_to_pixel``` and ```axis_world_coords``` that gets used if ```"TIME"``` is one of the axes.  If the kwarg is ```None``` and ```"TIME"``` is an axis, time since epoch is returned.

Any other ideas?

**Comment by DanRyanIrish** [comment]
ping @BaptistePellorceAstro and @Cadair

**Comment by Cadair** [comment]
I will give this some thought, but we should use astropy Time rather than datetime.

**Comment by DanRyanIrish** [comment]
Expected new features in astropy 3.2 should make this much easier.  Watch this space!
