### ISSUE TITLE
Return all dependant axes from `pixel_to_world`

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#117]
if you crop out lat, when you do a `pixel_to_world` it should still return lat (i.e. it should always return all the dependant axes)

**Comment by DanRyanIrish** [comment]
How should the output be formatted?  Should dependent axes' coords be linked in a tuple, so the length of the returned object is still the same as the number of data dimensions?  Should a world_axis_physical_types tuple be returned so it's clear what physical types each element is?

**Comment by DanRyanIrish** [comment]
The simplest would be three tuples, the first giving the coordinate values, second giving the coordinate types, and the third axis the data axis numbers.  Although that's not very self-explanatory.

As a first go, mainly to just get the functionality in here, how about we also return a list/tuple of the data axis numbers to which each element in the list or coordinate values corresponds?  Then we can wrap it under into a nicer output as a second step.

**Comment by Cadair** [comment]
I think we should just mark this as a wont fix in 1.0 and then in 2.0 migrate to using the APE 14 `world_to_pixel` API as discussed in #148

**Comment by DanRyanIrish** [comment]
Agreed.
