### ISSUE TITLE
Issue installing ndcube

### ISSUE THREAD

**Issue by ceb8** [sunpy/ndcube#119]
When I install ndcube and then import I get the following message:
```
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
```
If I update numpy using the conda-forge channel, and try to import ndcube again, I get an import error:
```
ImportError: Numpy version 1.9.0 or later must be installed to use Astropy
```

I am doing all of this in a new clean conda environment that I create with python 3.6, astropy and matplotlib. I then install sunpy from the conda-forge channel and then install ndcube, also from the conda-forge channel as in the readme.

**Comment by Cadair** [comment]
Thanks for the bug report @ceb8 I will have to check the conda package. What platform are you using?

**Comment by DanRyanIrish** [comment]
Hi @ceb8.  That's for letting us know this.  I've encountered this problem before with @MSKirk.  We found it was fixed by updating to conda 3.5.  We also updated numpy through conda, rather than conda-forge.  @MSKirk, do you remember if there was there anything more to fixing this?

Since this is more than just a once off, we should try to better advertise/understand how to avoid this in our documentation.

**Comment by MSKirk** [comment]
I solved it in a hack-y sort of way by manually changing the version of `numpy` to find a stable version with `NDCube`. This problem was fixed for me when I upgraded conda which then let me update `numpy` in the stack as well.  I am using `numpy` version 1.14.2 with conda 4.5.1.

**Comment by DanRyanIrish** [comment]
@MSKirk means he did the hack-y fix first which worked.  But then went back to the original set-up to find a better solution.  And that solution was to update conda.  So if you do that, you don't have to manually find a numpy version that works.

And thanks @MSKirk for pointing out that the upgraded conda version was 4.5, not 3.5 as I incorrectly typed before ;)

**Comment by ceb8** [comment]
I updated my conda, then did `conda update --all` and then installed ndcube again and it all worked!  Ndcube did update numpy and scipy even thought I'd just updated everything:
```
numpy:  1.14.2-py36ha9ae307_1             --> 1.14.3-py36_blas_openblas_200 conda-forge [blas_openblas]
scipy:  1.0.1-py36hcaad992_0              --> 1.1.0-py36_blas_openblas_200  conda-forge [blas_openblas]
```
but it all seems to be working so yay!

Maybe just add a minimum conda version to the list of requirements?

**Comment by DanRyanIrish** [comment]
Glad to hear you've fixed this issue @ceb8!  And thanks for the heads up.  @Cadair is playing with the conda recipe, but assuming that doesn't fix it, we should make conda 4.5 a requirement, or at least highly recommended in the documentation.

Thanks again!

**Comment by Cadair** [comment]
I have just pushed a new ndcube package to conda-forge, let me know if it fixes or breaks anything!!

**Comment by DanRyanIrish** [comment]
Thanks @Cadair

**Comment by Cadair** [comment]
That's because the mayavi package in the defaults channel is python 2 only and ndcube is python 3. Replace "anaconda" with "conda-forge" in the command and try again.
