### ISSUE TITLE
MetaData class or property for NDCubeSequence

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#120]
A new feature request for a metadata class for ```NDCubeSequence``` along the lines of the SunPy ```TimeSeries``` metadata class.  Analagous to (but not the same as) the SunPy ```TimeSeries``` class, ```NDCubeSequence``` is made up of a collection of objects each with their own meta data.  In the case of ```TimeSeries``` it may be that columns and/or different periods come from different files, each with different metadata.  In the case of ```NDCubeSequence```, it is made up of different ```NDCube```s each with its own ```meta``` attribute.  Instead of duplicating the common cube metadata in the ```NDCubeSequence.meta``` attribute, I suggest a metadata class or property that can dynamically return information from all the sub-cubes as well as any sequence level metadata.  The implementation could look something like this:
* sequence level metadata entered by the user during the initialisation of the ```NDCubeSequence``` could be stored in a hidden attribute ```NDCubeSequence._meta```.
* The ```meta``` attribute would then be a class or property that returned a class/dict containing the metadata from all cubes and the hidden ```_meta``` sequence attribute.
* Metadata keys that are common to all cubes can be returned as a key with a single value/Quantity.
* Metadata keys whose values differ between cubes could be returned as a array/Quantity, with values in the same order as the cubes in the sequence.
* Sequence level metadata would be returned as single value keys.

The advantages to a system like this include that:
* all the metadata could be accessed from the ```NDCubeSequence``` level in a neat fashion.
* ```NDCube``` metas are not altered in the tidying up process and so does not introduce complications when slicing, e.g. because common meta has been moved out of a sub-cube.
* If this property is slow, users can still write code accessing the sub-cube ```meta```s of the sequence ```_meta``` directly.
* What metadata is common to or varying through sub-cubes can be quickly determined.

There may be other advantages I have forgotten to list here too.

**Comment by sashank27** [comment]
Hey @DanRyanIrish I would like to tackle this one

**Comment by DanRyanIrish** [comment]
For the time being, this is being implemented on downstream packages.  See an example in the [sunraster](https://github.com/sunpy/sunraster/blob/master/sunraster/meta.py) package.
