### ISSUE TITLE
Slicing an NDCube with either a list or an array fails with an unhelpful error

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#128]
![image](https://user-images.githubusercontent.com/1391051/41853667-2f2b8942-7886-11e8-8e5f-e0aae72d6af9.png)

**Comment by Cadair** [comment]
There is no reason why passing in an iterable of valid slices shouldn't work. i.e. `ndcube[[10,10]] `ndcube[10,10]` are equivalent.

**Comment by Cadair** [comment]
After discussion with @DanRyanIrish we think this should just emit a nicer error.

**Comment by DanRyanIrish** [comment]
The error should go [here](https://github.com/sunpy/ndcube/blob/master/ndcube/utils/wcs.py#L209) in an ```else``` statement at the outermost level.
```python
else:
    raise TypeError("Slicing by FITS-WCS by {0} not supported.".format(type(item))
```
