### ISSUE TITLE
Move the documentation build to circleci and enable Giles

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#140]

**Comment by DanRyanIrish** [comment]
Can this issue now be closed @Cadair?

**Comment by nabobalis** [comment]
Err, circleci doesn't seem to be running on the last few open PRs. I am not sure why.

**Comment by nabobalis** [comment]
Someone with admin on circle needs to kick it. I can't seem to access any of the settings.

**Comment by nabobalis** [comment]
Oh hang on, it might work now. Would have to open a PR to check.

**Comment by DanRyanIrish** [comment]
Thanks @nabobalis!

**Comment by nabobalis** [comment]
If you can kick your open Pr and see if Circle comes back to life. Otherwise, we would have to delete the circleCI build and do it again but I don't think i have that power.
