### ISSUE TITLE
Transition to using the APE 14 API

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#148]
Now that APE 14 implementations exist for `astropy.wcs.WCS` and `gwcs.WCS` we should transition to using that API everywhere to be more agnostic to WCS implementation.

See https://github.com/astropy/astropy-APEs/blob/master/APE14.rst and http://docs.astropy.org/en/stable/wcs/wcsapi.html#wcsapi

**Comment by yashrsharma44** [comment]
I saw this project in the [GSoC 2019'](https://openastronomy.org/gsoc/gsoc2019/#/projects?project=incorporate_powerful_new_wcs_api_into_ndcube) and was planning to make the proposal. 
Can you guys give some insights about the project?
What I understand, after reading through the description, is that the `NDCube` needs to make the transition to use the new API, hence `NDCube` should support any `WCS` be it `gWCS` or `FITS-WCS`.
Ping @DanRyanIrish

**Comment by DanRyanIrish** [comment]
Hi @yashrsharma44.  I'm really glad to hear you are interested in this and would very much encourage you to apply.

That's right.  The first step is to change over the the new API described by APE 14.  Once that's done, then we can write functions under-the-hood that will enable ndcube to support gWCS as well as FITS-WCS.

**Comment by yashrsharma44** [comment]
Thanks @DanRyanIrish for the response! Well, I was thinking that is gWCS is going to be integrated into `NDCube`, or we provide placeholder so that gWCS can be implemented later? Because I did not find the integration explicitly anywhere in [GSoC ideas](https://openastronomy.org/gsoc/gsoc2019/#/projects?project=incorporate_powerful_new_wcs_api_into_ndcube)

**Comment by DanRyanIrish** [comment]
Hi @yashrsharma44.  Yes you are correct.  The implementation of gWCS is not explicitly in the [GSoC ideas](https://openastronomy.org/gsoc/gsoc2019/#/projects?project=incorporate_powerful_new_wcs_api_into_ndcube) and so doesn't have to be part of the project.  But the ultimate goal is that the API will be enable us to hook into either WCS or gWCS objects in the same way.  This will likely require at least some gWCS-specific code to be written and this could be included in this project if the conversion of the API goes smoother/quicker than we think.

**Comment by yashrsharma44** [comment]
Hey @DanRyanIrish , I have submitted a proposal, so can you have look?
[Link](https://github.com/sunpy/sunpy/wiki/GSoC-2019,-Yash-Sharma)

**Comment by Cadair** [comment]
Glue has implemented a bunch of APE 14 wcs helpers here: https://github.com/glue-viz/glue/blob/master/glue/utils/wcs.py which we should ~steal~ use as per the terms of the licence :stuck_out_tongue: .

**Comment by DanRyanIrish** [comment]
Looks good to me @yashrsharma44 !

**Comment by Cadair** [comment]
Also, there is ongoing work in astropy (https://github.com/astropy/astropy/pull/8546) to provide a framework for slicing which should make this even more generalisable.
