### ISSUE TITLE
Make the sunpy dependency optional

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#149]
We could make the dependency on the visualisation tools in SunPy optional, i.e only include the plotting mixin if SunPy is importable etc.

Certainly we should consider being able to import a version of ndcube without the plotting addons without SunPy installed.

**Comment by DanRyanIrish** [comment]
I'm OK with this.  Not sure how it would work in practice in the code.  But in principle all for it.

**Comment by DanRyanIrish** [comment]
Alternatively, since the animator is the only thing in sunpy on which ndcube depends, the animator could become its own package.  Then sunpy and ndcube could depend on it and users could use the animator in isolation.
