### ISSUE TITLE
Lazy loading data into ndcube with Dask

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/ndcube#184]
I'd like to lazily load a bunch of FITS files into an `NDCube`, e.g. 24h worth of AIA 171 data such that the actually data is not loaded into memory, but the ndcube object is aware of all the metadata from the headers. 

Ideally, I'd then like to be able to perform operations on this data (e.g. slice, average, sum) and have them be lazily executed. 

As far as I can tell, this is not currently possible. Roughly speaking, what changes would need to be made to support lazy loading data with Dask into an `NDCube`? Is this on the roadmap or out of the scope of the project? I'm happy to put some time into adding this functionality if it is feasible.

**Comment by Cadair** [comment]
Are you asking if NDCube could provide the functionality to load these files into an NDCube for you, or if NDCube supports being passed a dask array? (The latter should work).

If the FITS files are co-aligned you would need to construct or extend a WCS which also has a temporal axis. If they are not co-aligned then it get's much trickier. I wonder if NDCubeSequence could facilitate conversion to NDCube if the elements of the sequence are co-aligned in world and pixel space. Then it could handle the WCS.

As for the FITS I/O dask side, I am still not sure where's best to put that functionality.

**Comment by wtbarnes** [comment]
I'm really asking for both I guess.

Taking the case where I have a stack of FITS files in time that are all co-aligned, I'd like to be able to throw a list of files at NDCube and have it create a Dask array and a WCS with a temporal axis. Of course this could also just be a preprocessing step before loading into NDCube. 

Once the data is in NDCube say as a Dask array + the appropriate WCS, can I do lazily-evaluated coordinate-aware slicing? i.e. `crop_by_coords` returns an NDCube with the data stored as a Dask array including the task graph for the slicing.

I agree that the case where they are not co-aligned is quite a different story and probably involves a completely different data structure. Maybe NDCubeSequence (or MapSequence)? Ideally, this container would be able to create a co-aligned NDCube by distributing the embarassingly parallel prep-derotate computations across a cluster and then collecting them back and stacking them into a Dask array. This is probably outside the scope of NDCube, but I think is much easier given that collection is "loose" in the sense that they individual Maps don't need to share much metadata.

**Comment by Cadair** [comment]
There is no reason why constructing an NDCube with a dask array shouldn't work, and all the operations shoudn't cast to numpy anywhere, I would consider anything like that a bug.

I would love to see this Dask functionality integrated with NDCube, I am not sure about the best ways of doing it. I think something along the lines of stack of FITS > NDCubeSequence > NDCube would work, you would need a way to tell the NDCubeSequence to construct Dask rather than numpy on load though.

Maybe the answer here is some layer ontop of the actual NDCube* objects which does this. Alternatively some class methods could also work. `NDCubeSequence.dask_from_fits("path/to/file")` type things.

**Comment by wtbarnes** [comment]
So after playing around with this, it seems that it just works. 🎉 

There's really no friction at all when it comes to passing a Dask array to `NDCube` though I've not done a systematic test of all features. Same with `NDCubeSequence`.

I'll close this for now and reopen if I come across any actual issues.

Maybe an example should be included in the docs to show off this feature to users?

**Comment by Cadair** [comment]
An example sounds like a great idea.
