### ISSUE TITLE
Iterating over NDCubeSequence very slow with many "large" NDCubes

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/ndcube#190]
When iterating over an `NDCubeSequence` with many `NDCube`s is sluggish when each `NDCube` is relatively large (e.g. a 1000-by-1000 image). This seems to be because `__getitem__` calls `utils.sequence.slice_sequence`.

Is this needed when simply iterating through the cubes in a sequence? I find this a bit unexpected.

As a side note, iterating over `seq.data` is quite quick, likely because it avoids any slicing.

## Minimal Working Example

```python
>>> import ndcube
>>> import astropy.wcs
>>> wcs = astropy.wcs.WCS(
            {'CTYPE1': 'HPLN-TAN', 'CUNIT1': 'deg', 'CDELT1': 1, 'CRPIX1': 1, 'CRVAL1': 1, 'NAXIS1': 1000,
             'CTYPE2': 'HPLT-TAN', 'CUNIT2': 'deg', 'CDELT2':1, 'CRPIX2': 1, 'CRVAL2': 1, 'NAXIS2': 1000,})
>>> cubes = [ndcube.NDCube(np.random.rand(*wcs.array_shape), wcs, meta={'index': i}) for i in range(100)]
>>> seq = ndcube.NDCubeSequence(cubes)
>>> for i in seq:  # This is slow
        print(i.meta['index'])
>>> for i in seq.data:  # This is fast!
        print(i.meta['index'])
```

**Comment by DanRyanIrish** [comment]
Thanks for this comment @wtbarnes.  You're right that iterating over ```seq.data``` is the best way but not the default.  There is an issue open to simplify the ```NDCubeSequence``` slicing.  Hopefully this should speed up iteration as it will not call ```utils.sequence.slice_sequence``` if the slice item is an ```int``` and instead will simply do ```seq.data[item]```.  However, if this does not speed up the process for some reason, you could explicitly implement and the ```__iter__``` and ```__next__``` methods on ```NCubeSequence```.  Thus you could make ```for i in seq:``` equivalent to ```for i in seq.data:```.

**Comment by wtbarnes** [comment]
Just to give a bit more context here, on v1.4,

```python
%%timeit
for i in seq: 
    _ = i.meta['index']
```

gives 66.4 µs ± 181 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each) and

```python
%%timeit
for i in seq.data: 
    _ = i.meta['index']
```

gives 14.2 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each).

While the former is still nearly 4 times slower, this used to take over 10 seconds on `ndcube<=1.2` so I would say this is fixed.
