### ISSUE TITLE
PyPI package missing documentation

### ISSUE THREAD

**Issue by ViviCoder** [sunpy/ndcube#211]
When downloading version 1.2.0 of ndcube on PyPI, I noticed that it is missing documentation.
In addition, it contains prebuilt Python objects (*.pyc) in the astropy_helpers directory.

**Comment by Cadair** [comment]
heh looks like the release of SunPy I just did suffers from this bug as well.

**Comment by Cadair** [comment]
I have now released 1.2.1 which hopefully fixes this. Thanks!
