### ISSUE TITLE
No easy way to add a colorbar for a 2D ndcube plot

### ISSUE THREAD

**Issue by dstansby** [sunpy/ndcube#217]
Currently `NDCube.plot()` only returns the `WCSAxes` instance and not the plotted image, which means it's not possible to add a colorbar post-plotting. I think it should be possible to do something like this SunPy example with NDCube objects: https://docs.sunpy.org/en/stable/generated/gallery/plotting/map_editcolormap.html#sphx-glr-generated-gallery-plotting-map-editcolormap-py

**Comment by DanRyanIrish** [comment]
This raises the issue of what types plot should return and should preferably decided, or at least discussed, for 2.0.

**Comment by Cadair** [comment]
We could borrow this: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L2157 to make `plt.colorbar` work.

**Comment by DanRyanIrish** [comment]
Do this when a 2D plot is returned.
