### ISSUE TITLE
Should `NDCubeSequence.dimension` return Quantity.pixel for 0th dimension (i.e. the number of NDCubes) 

### ISSUE THREAD

**Issue by hayesla** [sunpy/ndcube#255]
I found it a little bit confusing that that in an `NDCubeSequence` when you do a `NDCubeSequence.dimension`, all the dimensions are in pixel quantities when the first dimension is the number of `NDCubes`. After chatting with @DanRyanIrish, I guess this makes sense when you think of the `NDCubeSequence` as a large sliceable array-like structure, however it is still a little bit not intuitive I think? However I don't know what the solution should be, and it probably is more correct to have it in the current way.

For example:
From the docs, let's say we have an NDCubeSequence consisting of 3 NDCubes, with each NDCube having a shape (3, 4, 5).

What we get is:
```
>>> my_sequence.dimensions 
       (<Quantity 3. pix>, <Quantity 3. pix>, <Quantity 4. pix>, <Quantity 5. pix>)
```

I guess my thoughts on this were that given the dimensions are returned as pixel units, you should be able to do `my_sequence.data` and it should return an ndarray with dimensions (3, 3, 4, 5), however this actually returns the list of `NDCubes`

However just note this is probably just down to my own confusion!

**Comment by DanRyanIrish** [comment]
This is great user feedback and should be considered.  The question is whether we want users to think of and interact with ```NDCubeSequence``` as:
1. a glorified list of ```NDCube```s, or;
2. a sliceable array-like, coordinate-aware, metadata enabled object in its own right.

If case 1, then pixel units of the sequence axis is confusing and there should be no issue with users accessing the ```.data``` attribute.  But raises the question, what is the difference between ```NDCubeSequence``` and a ```list``` of ```NDCube```s?  However, this approach may well be an intuitive perspective in many ways.

If the 2nd case, there users should never access the ```.data``` attribute unless they are looking to open up the box that is ```NDCubeSequence``` and "void the warranty".  Instead they should think about the ```NDCubeSequence``` in the same way they think about a larger ```NDCube``` object, i.e. they slice the ```NDCubeSequence``` as a whole.  In this case there is no difference between the sequence axis and the cube axes.  To the user, they are all just ```NDCubeSequence``` axes and so should look the same in 
```python
>>> my_sequence.dimensions 
```
