### ISSUE TITLE
Confusing text in docs

### ISSUE THREAD

**Issue by hayesla** [sunpy/ndcube#256]
After going through the slicing docs for `NDCubeSequence`, I found this sentence quite confusing and difficult to follow:

_Say we want to obtain a region of interest between the 1st and 2nd pixels (inclusive) in the 2nd dimension and 1st and 3rd pixels (inclusive) in the 3rd dimension of the 0th slice along the 0th axis in only the 1st (not 0th) and 2nd sub-cubes in the sequence_

The code below is a bit more intuitive, and maybe the text should reflect this better

`regions_of_interest_in_sequence = my_sequence[1:3, 0, 1:3, 1:4]`
where `my_sequence` is an `NDCubeSequence` of three `NDCubes` each of dimensions (3, 4, 5) (i.e. from https://docs.sunpy.org/projects/ndcube/en/stable/ndcubesequence.html#slicing)

I think it would make more sense to say that explicitly something along the lines that the the 0th index of `my_sequence` is the `NDcubes` on which to perform the slicing (i.e. in this case the 1st and 2nd cube). Then from this we can then slice the array of 3 dimensions with a shape (3, 4, 5). We want a region of interest from the 0th axis, the indices between the 1st and 2nd pixels (inclusive, i.e. [1:3]) in the 2nd axis dimension and the 1st and 3rd pixels (inclusive, i.e. [1:4]) in the 3rd dimension. Another way of thinking about this is you want to slice the individual NDCubes such that you have NDCube[0, 1:3, 1:4], but along the common axis and only for the 1st and 2nd cube in this example.

I don't know if my example is more confusing, but maybe we can think of providing a clearer picture of what this is doing, even with a diagram or something! :)

**Comment by DanRyanIrish** [comment]
Thanks for this insight @hayesla.  It's especially helpful to know that it is not obvious that the 0th axis of the ```NDCubeSequence``` refers to the axis along which the ```NDCube```s are stored.  I also agree that specific sentence is horrific.

Would you open a PR including your suggested change so we can all see how it fits in with the paragraph around it and we can iterate on it.

**Comment by DanRyanIrish** [comment]
This should be addressed as part of #289

**Comment by DanRyanIrish** [comment]
Addressed by #352
