### ISSUE TITLE
A concept of "Global Coordinates"

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#284]
The rework of extra coords in #271 excludes one use case for the extra_coords dict in 1.0, which is the concept of structured metadata describing the coordinates of the whole cube. i.e. "this (x,y,t) cube is at wavelength y nm".

We should consider adding some kind of functionality to NDCube 2.0 to represent these type of coordinates.

(N.B. this is something that could potentially be upstreamed into the APE 14 WCS interface at some point)

**Comment by Cadair** [comment]
A conversation at the PyHC meeting means we should consider this as a way to represent spacecraft location and maybe frame info.

**Comment by DanRyanIrish** [comment]
Would this be attached to the WCS?

**Comment by kakirastern** [comment]
Will start working on this issue shortly...

**Comment by DanRyanIrish** [comment]
Thanks @kakirastern!

**Comment by kakirastern** [comment]
Yeah, this would be a really great feature to have for Astropy conforming to the [APE 14 WCS](https://docs.astropy.org/en/stable/wcs/wcsapi.html)

**Comment by kakirastern** [comment]
Thanks @DanRyanIrish for the assignment. I will take it up later today HKT during the weekly community meeting.

**Comment by DanRyanIrish** [comment]
In the case of slicing out axes, the coord value at which the slice was made will be stored in this ```low_level_wcs``` property from astropy 4.2: https://github.com/astropy/astropy/pull/10195/files#diff-3976bdca12d482d3c3b404875b2db43f9cb04a37f674e17089d3520cced2a72dR157

**Comment by Cadair** [comment]
```python
class GlobalCoords:
    """
    A structured representation of coordinate information applicable to a whole NDCube.
    """
    def __init__(self, ndcube):
        pass

    def add(self, name, physical_type):
        """
        Add a new coordinate to the collection.
        """

    def remove(self, name):
        """
        Remove a coordinate from the collection
        """

    @property
    def names(self):
        """
        A tuple of all the names.
        """

    @property
    def physical_types(self):
        """
        A tuple of all physical types, one per coordinate.
        """

    def keys(self):
        """
        A set-like of all names in this collection.
        """

    def values(self):
        """
        A set-like of all values in this collection
        """

    def __getitem__(self, item):
        """
        Index the collection by a name.
        """
```

**Comment by kakirastern** [comment]
Will start working on this today HKT

**Comment by kakirastern** [comment]
How about adding an `update()` besides `add()` and `remove()`for `GlobalCoords`? Or am I complicating things?

**Comment by Cadair** [comment]
update is a dict-like API, the issue is that as well as the key (name) we also have physical type which needs to be present, hence sticking with `Mapping` and custom `add` and `remove` methods, rather than `MutableMapping`.

**Comment by kakirastern** [comment]
I see. Thanks for the clarification ❤️!
