### ISSUE TITLE
Documentation for ndcube 2

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#289]
This is a generic placeholder for the large documentation rebuild needed for 2.0.

I also wrote this: https://demo.codimd.org/54dm5gPMQmmJux6fV-3AOQ# the other day which might have a home in the docs.

**Comment by kakirastern** [comment]
Did a first check and some editing on the doc... Will come back for a second read over the next few days.

**Comment by DanRyanIrish** [comment]
In doing this we should address #256

**Comment by Cadair** [comment]
Also when doing this we should remove the doctest skip directives added in #271

**Comment by DanRyanIrish** [comment]
Much of this issue is addressed by the merging of #352.  However there are still remaining issues.  @Cadair can you outline what these are?
* The API docs need to show inherited attributes.
* The NDCubeSequence plotting section will have to be updated for the new animator.
Anything else?
