### ISSUE TITLE
Support reductions along an axis

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#290]
i.e. provide a way to sum along an axis which also modifies the wcs / extra_coords @SolarDrew

**Comment by DanRyanIrish** [comment]
Definitely would be handy.  Although this opens the wider question of resampling the cube.  I suggest this should not be labelled as crucial to 2.0 and can be included in a later release.

**Comment by DanRyanIrish** [comment]
From a technical point of view, this will be solved by #450.  However, does this feature request require a specific API that makes this easier?  For example, `NDCube.sum(axis=0)`?  This would be equivalent to `NDCube.superpixel((n,, 1, 1, ...), method="sum")` where `n` is the length of the 0th axis.  A similar method could exist for `mean`, `median`, `min` and `max`.

If the `axis` kwarg was not provided, then `NDCube.median()`, (and `min` and `max`) would be equivalent to `NDCube.data.median()`.  However, `NDCube.sum()` (and `NDCube.mean()`) would have to return a different object (e.g. `NDData` or a new `ScalarCube`) that keeps `data` (`float`), `uncertainty` (`float` or scalar `NDUncertainty` if that's valid), `mask` (`bool`), `global_coords`, and `meta`, but discards `wcs` and `extra_coords`.  All coords from these objects will be transferred to `global_coords` as appropriate.

Finally, this functionality would also be served by an `NDCube.squeeze()` method that slices away any length-1 axes and returns the above `ScalarCube` if all axes are length-1.

Any thoughts @Cadair?
