### ISSUE TITLE
Adding a 1D SkyCoord extra coordinate along a single array axis doesn't seem to work

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#340]
:bug:

**Comment by DanRyanIrish** [comment]
Does this refer to cases where the 2nd celestial axis has been sliced away/doesn't exist?  For example a slit spectrometer without a rastering axis?

**Comment by Cadair** [comment]
This is the case where you want to add a spatial extra coord which is only tied to one pixel axis. So yes, your example of a slit spectrometer without a rastering axis would be such a dataset.

**Comment by Cadair** [comment]
I can't reproduce this, infact we already have tests for it.
