### ISSUE TITLE
Rename ExtraCoords.add_coordinate to .add.

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#348]
### Description

Rename `ExtraCoords.add_coordinate` and `ExtraCoords.remove_coordinate` should be changed to `.add` and `.remove` to be consistent with `GlobalCoords`.  This represents concensus reached on the SEP thread (sunpy/sunpy-SEP#51).  (See conversation thread below.)

add_coordinate: https://github.com/sunpy/ndcube/blob/master/ndcube/extra_coords/extra_coords.py#L179

**Comment by DanRyanIrish** [comment]
ping @Cadair

**Comment by Cadair** [comment]
We would want `remove_coordinate` as well then?

**Comment by Cadair** [comment]
(This should probably be a comment on the SEP as well)

**Comment by DanRyanIrish** [comment]
Consensus on SEP thread (https://github.com/sunpy/sunpy-SEP/pull/51) is that `ExtraCoords.add_coordinate` and `ExtraCoords.remove_coordinate` should be changed to `.add` and `.remove` to be consistent with `GlobalCoords`.

**Comment by DanRyanIrish** [comment]
@rosteen, this is another conceptually simple issue that needs fixing for 2.0.

**Comment by DanRyanIrish** [comment]
> We would want `remove_coordinate` as well then?

@Cadair, what do you say to making the creation of `ExtraCoords.remove` a 2.1 goal?

**Comment by DanRyanIrish** [comment]
Wait.  `ExtraCoords.remove` might be needed when an axis is sliced away?

**Comment by DanRyanIrish** [comment]
The addition of a `ExtraCoords.remove` method has been moved to #395
