### ISSUE TITLE
master failing for devdeps

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#364]
### Description

https://dev.azure.com/sunpy/ndcube/_build/results?buildId=12187&view=logs&jobId=f4d09fca-9293-5bbb-a9bb-f818f18070eb&j=f4d09fca-9293-5bbb-a9bb-f818f18070eb&t=363d9b3b-2c68-5cb6-28ed-07d33424cb03

### Steps to Reproduce

```python
Code goes here
```

### System Details

- SunPy Version:
- Astropy Version:
- Python Version:
- OS information:

**Comment by DanRyanIrish** [comment]
Having discussed with @Cadair this is caused by a bug introduced in gwcs.

**Comment by Cadair** [comment]
gWCS got a new release yesterday, so this might no longer just be devdeps

**Comment by DanRyanIrish** [comment]
Would you still class this as a bug in gwcs that has made it to release?  Or is a feature thwat we want changed in gwcs or worked around in ndcube?

**Comment by DanRyanIrish** [comment]
This appears to be fixed.
