### ISSUE TITLE
HECR not recongnised as a physical type

### ISSUE THREAD

**Issue by dstansby** [sunpy/ndcube#366]
### Description
Thompson 2006 says I should be able to use `HECR` as a CTYPE to denote "Radial distance from sun center". However, ndcube doesn't seem to recognise this as a physical type:

```python
import astropy.wcs
import numpy as np

from ndcube import NDCube

# Define data array.
data = np.random.rand(4, 4, 5)
# Define WCS transformations in an astropy WCS object.
wcs = astropy.wcs.WCS(naxis=3)
wcs.wcs.ctype = 'HECR', 'HPLT-TAN', 'HPLN-TAN'
wcs.wcs.cunit = 'Angstrom', 'deg', 'deg'
wcs.wcs.cdelt = 0.2, 0.5, 0.4
wcs.wcs.crpix = 0, 2, 2
wcs.wcs.crval = 10, 0.5, 1

# Now instantiate the NDCube
my_cube = NDCube(data, wcs=wcs)
print(my_cube.array_axis_physical_types)
```
gives
```python
[('custom:pos.helioprojective.lat', 'custom:pos.helioprojective.lon'), ('custom:pos.helioprojective.lat', 'custom:pos.helioprojective.lon'), (None,)]
```
Note that the last entry is `None`. I would expect it to be `pos.distance` looking at https://www.ivoa.net/documents/REC/UCD/UCDlist-20070402.html.

This is on the current RC of ndcube.

**Comment by Cadair** [comment]
It would need adding to the dict in utils/wcs.py :)
