### ISSUE TITLE
What order is the plot_axes list in?

### ISSUE THREAD

**Issue by dstansby** [sunpy/ndcube#368]
`plot` has a `plot_axes` argument, but it's not clear from the [docstring](https://docs.sunpy.org/projects/ndcube/en/v2.0.0b2/api/ndcube.mixins.NDCubePlotMixin.html) whether the order of this list should be `NAXIS1, NAXIS2...` or correspond to the axes of the input data (which are the reverse order of NAXIS1, NAXIS2 etc.).

**Comment by Cadair** [comment]
Should be array order, so the reverse of the FITS header.
