### ISSUE TITLE
Add a way to have custom coordinate names?

### ISSUE THREAD

**Issue by dstansby** [sunpy/ndcube#370]
As an example, there are lots of plots on https://docs.sunpy.org/projects/ndcube/en/latest/visualization.html that have axes labelled as `custom.pos.helioprojective.lon`, which is hard to read and very long.

Of course one can go through and manually edit all of these, but it would be nice when creating a `NDCube` if there was a way of supplying 'custom coordinate names', so NDCube automatically uses these coordinate names when labeling plots.

**Comment by Cadair** [comment]
if you set `wcs.cname` it will use those instead.
