### ISSUE TITLE
Should NDCube.crop support incomplete inputs?

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#379]
### Description

Currently, if you don't want to specify the range of a real world axis to `NDCube.crop`, you can insert a `None` in the relevant location of the corner inputs.  But if the user only wants to supply a subset of coordinate objects an doesn't want to supply the `None`s, or worry about the ordering, should `NDCube.crop` try to fill in the `None`s for the user?

For example, given a time-space-space cube:
```python
>>> cube.wcs.world_axis_physical_types
['custom:pos.helioprojective.lon', 'custom:pos.helioprojective.lat', 'time']
```
Say I user wants to crop using a `SkyCoord`.  They could do:
```python
>>> bottom_left = SkyCoord(-900 * u.arcsec, -900 * u.arcsec, frame=aia_map.coordinate_frame)
>>> top_right = SkyCoord(0 * u.arcsec, -200 * u.arcsec, frame=aia_map.coordinate_frame)
>>> cube.crop((bottom_left, None), (top_right, None))
```
But should they also be allowed to do:
```python
>>> cube.crop((bottom_left,), (top_right,))
```

`NDCube.crop` could use `cube.wcs.world_axis_object_classes` to infer where to place the inputs, assuming there is no repetition of physical types.  An improved version of the following code within `NDCube.crop` could achieve this for the `lower_corner` input:

```python
expected_classes = [val[0] for val in cube.wcs.world_axis_object_classes.values()]
n_classes = len(expected_classes)
class_indices = np.arange(n_classes)
if len(lower_corner) < n_classes:  # Only do this if user did not enter enough coordinate objects.
    blank_lower = np.array([None] * n_classes)  # Create a new blank lower corner input populated by Nones
    for obj in lower_corner:
        if obj is not None:  # In case users put in some None but not enough for lower_corner to be right length.
            idx = class_indices[[isinstance(obj, c) for c in expected_classes]]
            blank_lower[idx[0]] = obj  # Place object in the equivalent location of the first consistent object in expected_classes.
    lower_corner = list(blank_lower)  # Replace lower_corner with version with missing Nones inserted.
```
This would be repeated for the `upper_corner` input.

**Comment by DanRyanIrish** [comment]
Thoughts @Cadair?

**Comment by Cadair** [comment]
In general I think this is a good idea. Although it's not really

> assuming there is no repetition of physical types

It's assuming there is no repetition of classes in `world_axis_physical_types`?

I think we would need a well thought through function which checks the input is unique and then inserts the Nones.

**Comment by Cadair** [comment]
Also, this should combo with the not needing to specify a tuple. So you could just pass a couple of time objects for a 5d cube.

**Comment by DanRyanIrish** [comment]
> In general I think this is a good idea. Although it's not really

You mean in theory it's a good idea but not in practice?

> I think we would need a well thought through function which checks the input is unique and then inserts the Nones.

Agreed.  I think this is not necessarily trivial in the highly generalized world of ndcube.  I'm not convinced we should support it.  Although it's an interesting possibility and would probably be very helpful to users.

> Also, this should combo with the not needing to specify a tuple. So you could just pass a couple of time objects for a 5d cube.

For sure.  In fact, master should now allow single coordinate objects to be entered, at least if only one is needed to completely describe the world coordinate space, e.g. for `sunpy.map.Map`.

**Comment by Cadair** [comment]
> > In general I think this is a good idea. Although it's not really
> 
> You mean in theory it's a good idea but not in practice?

The quote block was in the middle of the sentence. I was saying that it's possible to have two identical physical types represented by different high level objects, so it's the list of objects not the list of types we would have to validate against.
