### ISSUE TITLE
NDcube should be able to be instantiated from another NDCube

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#385]
If this doesn't already work it should. This would allow you to instantiate a sunraster object from a DKIST user tools object for instance, which is probably something that people are going to want to do.

**Comment by DanRyanIrish** [comment]
I think this issue is the same as #372

**Comment by DanRyanIrish** [comment]
@rosteen, I think this issue might be a good one for you to work on next to help get closer to the 2.0 release.
