### ISSUE TITLE
STOKES CTYPE not registering with an axis physical type

### ISSUE THREAD

**Issue by hayesla** [sunpy/ndcube#387]
### Description
When `STOKES` is used as an axis type, the physical type is not registered (i.e. `phys.polarization.stokes`)

### Expected vs Actual behavior
The `STOKES` WCS CTYPE name does not register as a physical type - the physical type is `None` rather than `phys.polarization.stokes`

### Steps to Reproduce
```python
>>> import astropy.wcs
>>> import numpy as np

>>> from ndcube import NDCube

>>> data = np.random.rand(4, 5, 5)
>>> wcs = astropy.wcs.WCS(naxis=3)
>>> wcs.wcs.ctype = 'HPLT-TAN', 'HPLN-TAN', 'STOKES'
>>> wcs.wcs.cunit = 'deg', 'deg', ''
>>> wcs.wcs.cdelt =  0.5, 0.4, 1
>>> wcs.wcs.crpix =  2, 2, 0
>>> wcs.wcs.crval =  0.5, 1, 1


>>> my_cube = NDCube(data, wcs=wcs)
>>> my_cube.array_axis_physical_types
[(None,),
 ('custom:pos.helioprojective.lat', 'custom:pos.helioprojective.lon'),
 ('custom:pos.helioprojective.lat', 'custom:pos.helioprojective.lon')]
```
where the `None` should be `phys.polarization.stokes`

### Other
There is an issue such that its not registered with astropy https://github.com/astropy/astropy/blob/master/astropy/wcs/wcsapi/fitswcs.py#L88 however as  @Cadair has said it should be overwritten here https://github.com/sunpy/ndcube/blob/master/ndcube/utils/wcs.py#L35

**Comment by hayesla** [comment]
I've made a PR to astropy related to this https://github.com/astropy/astropy/pull/11236

**Comment by DanRyanIrish** [comment]
Thanks so much for this issue and the astropy PR @hayesla!

**Comment by hayesla** [comment]
this is now fixed in astropy via https://github.com/astropy/astropy/pull/11236

**Comment by Cadair** [comment]
Do we want to patch over this in ndcube as well?

**Comment by hayesla** [comment]
I would say yes (as I can imagine STOKES is going to be a good use case for NDCube)?

**Comment by Cadair** [comment]
Should be an easy patch.
