### ISSUE TITLE
Starting an example gallery

### ISSUE THREAD

**Issue by hayesla** [sunpy/ndcube#388]
### Description
I know I've been harping on about an example gallery - but I definitely think it would be a nice idea of showing some 'real-life' examples of the functionality of NDCube to build upon the docs. This could include some simple ones about how to get started to instantiate an NDCubewhen you have a data array and header read in from a fits file etc. 

I'm happy to get started with some simple examples

**Comment by Cadair** [comment]
Feel free to create an `examples/` directory and start putting things in there, I can perform the sphinx incantations when I have a little more time.

**Comment by DanRyanIrish** [comment]
Resolved by #537 and #549 enhanced by #544
