### ISSUE TITLE
Saving an NDCube

### ISSUE THREAD

**Issue by hayesla** [sunpy/ndcube#409]
### Description
After a recent discussion, I had with @grahamkerr, there may be a use case for `write` functionality of an NDCube (e.g. to a fits file). From what I can tell there doesn't seem to be one at the moment (however maybe I'm missing it?).

The easiest thing I guess would be to save the wcs and meta to a fits header and then save to a fits file with the nd-data array. However this may also not be a good idea, and maybe hard to generalize for sequence/collections.

But something to think about - any thoughts @DanRyanIrish @Cadair

**Comment by DanRyanIrish** [comment]
This is certainly something that has come up and documented in issue #111.  Let's redirect this conversation to that issue.
