### ISSUE TITLE
Robustly ensure the behaviour of `crop` is correct.

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#418]
SunPy's Map has had unlimited trouble with `submap` we need to make sure our semantics are correct before release: https://github.com/sunpy/sunpy-SEP/pull/51#discussion_r533597518

**Comment by Cadair** [comment]
It's not...

```python
import ndcube
import sunpy.map
import sunpy.data.sample
from astropy.coordinates import SkyCoord
import astropy.units as u

import matplotlib.pyplot as plt

aia = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
ndc = ndcube.NDCube(aia.data, aia.wcs)

bottom_left = SkyCoord(40*u.deg, -45*u.deg, frame='heliographic_stonyhurst', obstime=aia.date)
top_right = SkyCoord(50*u.deg, 45*u.deg, frame='heliographic_stonyhurst', obstime=aia.date)


sm = aia.submap(bottom_left, top_right=top_right)
sndc = ndc.crop(bottom_left, upper_corner=top_right)

print("Shape", sm.data.shape == sndc.data.shape, f"{sm.data.shape}, {sndc.data.shape}")
print("Bottom left pixel", sm.wcs.pixel_to_world(0, 0) == sndc.wcs.pixel_to_world(0, 0), f"{sm.wcs.pixel_to_world(0, 0)}, {sndc.wcs.pixel_to_world(0, 0)}")
```
```
Shape False (559, 36), (559, 34)
Bottom left pixel False <SkyCoord (Helioprojective: obstime=2011-06-07T06:33:02.770, rsun=696000000.0 m, observer=<HeliographicStonyhurst Coordinate (obstime=2011-06-07T06:33:02.770): (lon, lat, radius) in (deg, deg, m)
    (-0.00406308, 0.04787238, 1.51846026e+11)>): (Tx, Ty) in arcsec
    (428.08956417, -671.22221086)>, <SkyCoord (Helioprojective: obstime=2011-06-07T06:33:02.770, rsun=696000000.0 m, observer=<HeliographicStonyhurst Coordinate (obstime=2011-06-07T06:33:02.770): (lon, lat, radius) in (deg, deg, m)
    (-0.00406308, 0.04787238, 1.51846026e+11)>): (Tx, Ty) in arcsec
    (430.49233881, -671.22801665)>
```

**Comment by Cadair** [comment]
On further investigation this seems to be a bug in sunpy's submap: sunpy/sunpy#5461

**Comment by Cadair** [comment]
The issue is not sunpy's it's ours, running the above test with the `AIA_171_ROLL_IMAGE` clearly shows that we have a major issue:

```

Shape False (1652, 1652), (1652, 2)
Bottom left pixel False <SkyCoord (Helioprojective: obstime=2014-04-09T06:00:12.970, rsun=696000000.0 m, observer=<HeliographicStonyhurst Coordinate (obstime=2014-04-09T06:00:12.970): (lon, lat, radius) in (deg, deg, m)
    (-0.00589048, -6.04892164, 1.49860274e+11)>): (Tx, Ty) in arcsec
    (-449.98828983, 249.77241017)>, <SkyCoord (Helioprojective: obstime=2014-04-09T06:00:12.970, rsun=696000000.0 m, observer=<HeliographicStonyhurst Coordinate (obstime=2014-04-09T06:00:12.970): (lon, lat, radius) in (deg, deg, m)
    (-0.00589048, -6.04892164, 1.49860274e+11)>): (Tx, Ty) in arcsec
    (-100.15155868, -99.82889332)>
```


The issue is that crop is only using the two world coordinates specified not all 4 corners of the ROI specified by the two corners.

**Comment by DanRyanIrish** [comment]
After discussion on element between @Cadair and @DanRyanIrish, it was decided that the way forward will be:
* Create a private method that simply takes a list of `m` world coordinates, each described by `n` points where `n` (is the number of world dimensions) and finds the minimum pixel bounding box that includes these locations.  This is almost, although not exactly what `crop` currently does.
* Make `crop` a wrapper around this private function which takes `n` length-2 high-level coordinate objects.
  * `crop` will construct the 2^n world coordinates which describe all corners of the `n`-D world cube.
  * The points will be fed to the private function which will return the cropped cube.

There was discussion about whether the expose the private function as is could be useful to users to crop their cube to the minimum pixel size that includes the input points.  This has use cases including:
* Cropping to the minimum FOV that includes number of stars
* Cropping to a time and energy range that includes all occurrences in an event list, e.g. flares.
* perhaps others.

For now we won't commit to exposing this.  But having it as a private function will make it easy to expose in the future.
