### ISSUE TITLE
Accessing `axis_world_coords` is "slow" for "large" data cubes

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/ndcube#420]
### Description

For the case of data cubes composed of two spatial dimensions and a time dimension (e.g. an AIA cutout in time), the dimensions can often be large in the spatial dimension (several thousand pixels) and relatively shallow in the time dimension (tens to maybe a few hundred pixels). When trying to access the `axis_world_coords` for the (uncoupled) time dimension, this function can hang for several minutes, despite only returning a one-dimension time object. 

### Code Example

```python
import numpy as np
from astropy.wcs import WCS
import ndcube


def make_ndcube(dimensions):
    data = np.random.rand(*dimensions)
    wcs = WCS(naxis=3)
    wcs.wcs.ctype = 'HPLN-TAN', 'HPLT-TAN', 'TIME', 
    wcs.wcs.cunit =  'deg', 'deg', ''
    wcs.wcs.cdelt = 0.0001,  0.0001,  100 
    wcs.wcs.crpix = 0.0,  0.0,  1.0
    wcs.wcs.crval = -0.1,  -0.09,  0.0
    return ndcube.NDCube(data, wcs=wcs)
```

A very small spatial cutout does ok at a few ms,

```python
%%timeit -n 1 -r 1
make_ndcube((50,10,10)).axis_world_coords(0)
18.8 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

This is about ~15 times slower
```python
%%timeit -n 1 -r 1
make_ndcube((50,100,100)).axis_world_coords(0)
304 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

This takes over 30 s just to access the array for the time dimension.
```python
%%timeit -n 1 -r 1
make_ndcube((50,1000,1000)).axis_world_coords(0)
32.1 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

Particular for high-resolution imagers, 1000-by-1000 is a modest cutout size. At full temporal resolution and an observing time of a few hours, the time dimension may also be significantly longer. Accessing the corresponding time array for a data cube is a very common operation. I suspect that this may be large stumbling block for users if it takes minutes just to retrieve this array each time.

**Comment by Cadair** [comment]
Fixed in #442
