### ISSUE TITLE
Extend reproject method to support other algorithms

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#440]
## Outline

The `adaptive` and `exact` reproject algorithms are applicable to image axes only.  This is why PR #434 does not support them.  This issue summarizes the way forward for extending `NDCube.reproject_to` to those other algorithms.
* Initially, we will only support these algorithms in the case of a 2-D celestial `NDCube`.  (Supporting more general cases are discussed further below.)
* If user requests `adaptive` or `exact` to be used then check the original WCS.
  * If not 2-D, raise error
  * If 2-D but not celestial, raise error.
  * Otherwise proceed.

The question now is how to check for celestial axes.

## Checking For Celestial Axes
In order to fast-track this feature, we will use a shortcut for identifying celestial axes which we hope will work for most cases. (See below for the future more generalized approach.)

Check the physical types of the axes against a finite list options.  These will include that the physical type will include:
* `pos.` and `.lat` or `.lon`
* `.ra`
* `.dec`
* Add other cases here.

Because we hope to deal with this more generally in the future, we should check against the UCD1+ vocab list for other valid possibilities.  But beyond that we will encourage users to inform us of other cases which we can then add to our list.  Before this list gets too long we hope to have a more generalized implementation which will remove the need for this checklist.

## Future Generalized Implementation
In general, these algorithms should be valid for any >=2-D cube which contains two dependent spatial axes.  The reprojection could then be done in these two dimensions while keeping the rest unchanged.  To do this we need a way of identifying invariant axes.  This is discussed in #432.  Once that is implemented, we can leverage it remove the above limitations.

## Justification for Immediate Implementation
Supporting other algorithms for 2-D celestial cubes is needed by SunPy Map.  By using the above quick-and-dirty implementation, reproject can be released as part of 2.0 and enable Map to use reproject's full power.  The more generalized subsequent implementation will have no impact on Map's use case.

**Comment by DanRyanIrish** [comment]
ping @adwaitbhope.  Here is the summary of the way forward for supporting other reproject algorithms.

**Comment by Cadair** [comment]
I spoke to @astrofrog about this and he has already implemented a thing like this in reproject: https://github.com/astropy/reproject/blob/master/reproject/wcs_utils.py#L203 matching the physical types might not be the best approach.

**Comment by DanRyanIrish** [comment]
Looks like this tells us whether the WCS includes at least one celestial axis, but not whether the WCS is 2-D or if it is, that both axes are celestial.  But this looks like that function will definitely help us.

**Comment by adwaitbhope** [comment]
To determine if the axis is celestial, the function is checking if the coordinate type is a subclass of `SkyCoord`.
Will this work better or should we continue with our original discussion of using regex with the patterns described above?
