### ISSUE TITLE
Method for converting NDCube to new unit

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#469]
### Description

This issue proposes a new method, `NDCube.to()` that scales the data in an `NDCube` to a new unit.  This can be done by combining `NDCube.data` with `NDCube.unit` and using the astropy `Quantity` infrastructure to convert the data to new unit input by the user.

#### Proposed API
* Mimic the astropy `Quantity.to` API, i.e. `cube.to(unit)` where `unit` is a valid astropy unit object of unit string.
* Include an optional kwarg, `convert_uncertainty=True` which, when `True`, implies that the uncertainties are absolute, rather than fractional.  Therefore, the uncertainties are also scaled as well by assuming they are in the same unit as `NDCube.unit`.  If `convert_uncertainty=False`, the uncertainty values are left alone.
* `**kwargs` are passed onto `Quantity.to`.

**Comment by Cadair** [comment]
I think this should be a NDData issue?

**Comment by wtbarnes** [comment]
One potential pitfall: if you go the route of creating an intermediate `Quantity` to validate the unit conversion (similar to what we do with the arithmetic operations on `Map`) and your `.data` is represented as a Dask array, representing the `.data` + `.unit` as a `Quantity` will force an eager evaluation of your Dask array (i.e. put it into local memory).

**Comment by DanRyanIrish** [comment]
How would you avoid that?

**Comment by wtbarnes** [comment]
Sorry, I just saw that you had replied to this!

I'm not entirely sure. To me, this seems like an upstream issue for astropy. `Quantity` objects just do not play nice with Dask arrays. See for example astropy/astropy#1137.

**Comment by DanRyanIrish** [comment]
Addressed by #586
