### ISSUE TITLE
TST: CI py38-figure is missing figure hashes for Astropy 4.3.1

### ISSUE THREAD

**Issue by dhomeier** [sunpy/ndcube#494]
### Description
Tests in `py38-figure` fail with:
```
Failed: Can't find hash library at path /home/circleci/project/.tox/py38-figure/lib/python3.8/site-packages/ndcube/visualization/tests/figure_hashes_mpl_332_ft_261_astropy_431_animators_100.json
```

### Steps to Reproduce
See e.g. https://app.circleci.com/pipelines/github/sunpy/ndcube/1305/workflows/8f768cc8-1c1f-4194-a691-9ac70da60746/jobs/5238

**Comment by Cadair** [comment]
Fixed in #500
