### ISSUE TITLE
Potential bug with `crop_by_values`

### ISSUE THREAD

**Issue by hayesla** [sunpy/ndcube#496]
### Description

Came across an issue when trying to use `ndcube.NDCube.crop_by_values()` such that it either returns the same NDCube or otherwise errors with `ValueError: Input points causes cube to be cropped to a single pixel. This is not supported.`

It still could be something I'm doing wrong. Also documentation in examples uses should be added to the docs

### Steps to Reproduce

Here's an example, of trying to crop a NDCube which contains the data from an AIA image.

```python
>>> import sunpy.map
>>> from sunpy.data.sample import AIA_171_IMAGE
>>> from ndcube import NDCube
>>> from astropy import units as u
>>> from astropy.coordinates import SkyCoord
>>> from astropy.wcs.utils import wcs_to_celestial_frame


>>> my_map = sunpy.map.Map(AIA_171_IMAGE)
>>> my_ndcube = NDCube(my_map.data, my_map.wcs)

```
and `crop` works:

```python
>>> bl = SkyCoord(500*u.arcsec, -400*u.arcsec, frame=wcs_to_celestial_frame(my_ndcube.wcs))
>>> tr = SkyCoord(1100*u.arcsec, -200*u.arcsec, frame=wcs_to_celestial_frame(my_ndcube.wcs))
>>> my_ndcube.crop(bl, tr).dimensions
[85, 250]pix
```
however when trying to use `crop_by_values` there seems to be a bug

```python
>>> my_ndcube.crop_by_values((500*u.arcsec, -400*u.arcsec), (1100*u.arcsec, -200*u.arcsec)).dimensions
~/opt/miniconda3/envs/july_flare/lib/python3.9/site-packages/ndcube/utils/cube.py in get_crop_item_from_points(points, wcs, crop_by_values)
    195     # If item will result in a scalar cube, raise an error as this is not currently supported.
    196     if result_is_scalar:
--> 197         raise ValueError("Input points causes cube to be cropped to a single pixel. "
    198                          "This is not supported.")
    199     return tuple(item)

ValueError: Input points causes cube to be cropped to a single pixel. This is not supported.
```
 whats even weirder - if I change the bottom left y coord from -400'' to -500'', an error isn't raised, but it returns a NDCube with dimensions of [0,0] 🤷 

```python
>>> my_ndcube.crop_by_values((500*u.arcsec, -500*u.arcsec), (1100*u.arcsec, -200*u.arcsec))

<ndcube.ndcube.NDCube object at 0x7fc3918f5f70>
NDCube
------
Dimensions: [0. 0.] pix
Physical Types of Axes: [('custom:pos.helioprojective.lon', 'custom:pos.helioprojective.lat'), ('custom:pos.helioprojective.lon', 'custom:pos.helioprojective.lat')]
Unit: None
Data Type: float32
```
### System Details

- SunPy Version: 3.1.0
- Astropy Version: 4.3.1
- NDCube Version: 2.0.0

**Comment by DanRyanIrish** [comment]
Hi @hayesla.  I think there's something messed up with the WCS.
```python
>>> my_ndcube.wcs.pixel_to_world_values([0, 0, 1, 1], [0, 1, 0, 1])  # Returns values as floats in degrees.
(array([359.65867648, 359.6586781 , 359.6593439 , 359.65934552]),
 array([-0.34017347, -0.33950606, -0.34017511, -0.3395077 ]))
```
And so...
```python
>>> my_ndcube.wcs.world_to_pixel_values(500*u.arcsec, -400*u.arcsec)
(array(nan), array(nan))
>>> my_ndcube.wcs.world_to_pixel_values(1100*u.arcsec, -200*u.arcsec)
(array(nan), array(nan))
```
Since both world points get returned as `nan`, `NDCube.crop_by_values` assumed this means both worlc locations come from the same pixel which is why that specific error is raised.  But really it's because the underlying WCS can't resolve your world inputs to a pixel coordinate.

**Comment by Cadair** [comment]
Oh no, why does that not work with longitude wrapping.

**Comment by dhomeier** [comment]
It's not the wrapping, it's just ignoring the units!
```python
>>> my_ndcube.wcs.world_to_pixel_values(([500, 1100]*u.arcsec).to(u.deg), ([-400, -200]*u.arcsec).to(u.deg))
(array([718.65441842, 968.16540999]), array([344.95101584, 428.79182413]))
```

**Comment by dhomeier** [comment]
And the WCS seems to confuse its inputs in other ways as well; `world_to_pixel_values` works the same with the Nx2 array form, but `world_to_pixel` raises with the latter:
```python
>>> my_ndcube.wcs.pixel_to_world_values([0, 0, 1, 1], [0, 1, 0, 1])
(array([359.65867648, 359.6586781 , 359.6593439 , 359.65934552]), array([-0.34017347, -0.33950606, -0.34017511, -0.3395077 ]))
>>> my_ndcube.wcs.pixel_to_world_values([[0, 0], [0, 1], [1, 0], [1, 1]])
(array([ 3.59658676e+02, -3.40173465e-01]), array([ 3.59658678e+02, -3.39506061e-01]), array([ 3.59659344e+02, -3.40175106e-01]), array([ 3.59659346e+02, -3.39507701e-01]))

>>> my_ndcube.wcs.pixel_to_world([0, 0, 1, 1], [0, 1, 0, 1])
<SkyCoord (Helioprojective: obstime=2011-06-07T06:33:02.770, rsun=696000.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=2011-06-07T06:33:02.770, rsun=696000.0 km): (lon, lat, radius) in (deg, deg, m)
    (-0.00406308, 0.04787238, 1.51846026e+11)>): (Tx, Ty) in arcsec
    [(-1228.76466158, -1224.62447509), (-1228.75883987, -1222.22181793),
     (-1226.36196228, -1224.63038192), (-1226.35614057, -1222.22772459)]>
>>> my_ndcube.wcs.pixel_to_world([[0, 0], [0, 1], [1, 0], [1, 1]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.9/site-packages/astropy/wcs/wcsapi/high_level_api.py", line 324, in pixel_to_world
    pixel_values = values_to_high_level_objects(*world_values, low_level_wcs=self.low_level_wcs)
  File "/opt/lib/python3.9/site-packages/astropy/wcs/wcsapi/high_level_api.py", line 291, in values_to_high_level_objects
    result.append(klass_gen(*args[key], *ar, **kwargs[key], **kw))
  File "/opt/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate.py", line 331, in __init__
    skycoord_kwargs, components, info = _parse_coordinate_data(
  File "/opt/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate_parsers.py", line 296, in _parse_coordinate_data
    _components[frame_attr_name] = attr_class(arg, unit=unit)
  File "/opt/lib/python3.9/site-packages/astropy/coordinates/angles.py", line 564, in __new__
    self._validate_angles()
  File "/opt/lib/python3.9/site-packages/astropy/coordinates/angles.py", line 585, in _validate_angles
    raise ValueError('Latitude angle(s) must be within -90 deg <= angle <= 90 deg, '
ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got [ 3.59658678e+02 -3.39506061e-01] deg
```

**Comment by Cadair** [comment]
> It's not the wrapping, it's just ignoring the units!

oh no.

**Comment by Cadair** [comment]
Ok, so I think the root of this issue is what I would consider an Astropy bug, which is the FITS-WCS implementation of LowLevelWCS is silently ignoring units in it's implementation of `world_to_pixel_values`. 

While the APE 14 spec states:

> This method takes n_world scalars or arrays as input in units given by `world_axis_units`.

it doesn't say you can or should ignore units if you are given them (although it also doesn't tell you explicitly you can't)

To further justify why I think this is an astropy bug gWCS dosen't do this:
```
In [8]: ds.wcs.world_to_pixel_values(-100*u.arcsec,-100*u.arcsec,0)
Out[8]: (24.47718333277509, 24.477178864241885, 0.0)

In [9]: ds.wcs.world_to_pixel_values((-100*u.arcsec).to(u.deg),-100*u.arcsec,0)
Out[9]: (24.47718333277509, 24.477178864241885, 0.0)
```

---

In the short term, the ndcube implementation of `crop_by_values` needs patching to convert the quantity objects it is given as input to the units given by `wcs.world_axis_units` before it calls `wcs.world_to_pixel_values` just to be on the safe side. I shall open a PR to Astropy to fix the underlying bug upstream.

**Comment by DanRyanIrish** [comment]
Having looked into what is required for the patch, perhaps this is something @hayesla might like to take on.  The patch itself should actually be quite simple.  Most of the effort will be in understanding the bit of the code base to know where the change is required.  It could be a good learning opportunity and shouldn't take too much effort.  The steps I would recommend are:
1. Write a test in `test_ndcube.py` that replicates this bug and make sure it fails as expected.
2. Replace the last few lines of [`NDCube._get_crop_by_values_item`](https://github.com/sunpy/ndcube/blob/main/ndcube/ndcube.py#L519) with a line that converts each `Quantity` in each point (`points[i][j]` in the code) to the correct unit stored in `wcs.world_axis_units`.  Then the last line of that method will enter the converted points to `utils.cube.get_crop_item_from_points` (and hence `wcs.world_to_pixel_values`) correctly.
3. Confirm the fix now makes the test pass.

What do you think @hayesla?
