### ISSUE TITLE
CTYPE-to-UCD Mapping of `SOLX`, `SOLY` not respected

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/ndcube#507]
According to this lookup table in astropy,

https://github.com/astropy/astropy/blob/b740594dcc9f8aacae0c14a5774e09f0732d1aef/astropy/wcs/wcsapi/fitswcs.py#L106-L108

the `SOL{X,Y,Z}` CTYPES should map to `custom:pos.heliocentric.{x,y,z}`. However, when creating a WCS with these ctypes, these mappings do not apppear to be respected with astropy, e.g.

```python
>>> import astropy.wcs
>>> foo = astropy.wcs.WCS(naxis=3)
>>> foo.wcs.ctype = ['SOLX', 'SOLY', 'SOLZ']
>>> print(foo.world_axis_physical_types)
[None, None, None]
```

This is more of an upstream astropy issue, but I believe this ctype-to-ucd mapping was added upstream for ndcube-specific reasons.

Astropy version: 4.2

**Comment by dhomeier** [comment]
The 'SOL*' types were only added to `CTYPE_TO_UCD1` in 4.3x; works for me as expected with 4.3.1 and 5.0rc2:
```python
>>> foo.world_axis_physical_types
['custom:pos.heliocentric.x', 'custom:pos.heliocentric.y', 'custom:pos.heliocentric.z']
```

**Comment by wtbarnes** [comment]
Ah yep that was my problem 🤦 Somehow I thought they had been added before that.
