### ISSUE TITLE
Make decision on whether to remove NDCubeOrdered for 1.0

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#51]
Should ```NDCubeOrdered``` be removed for 1.0.  The idea of an ordered WCS is a legacy from ```sunpycube``` which assumed an axes order in carrying out its operations.  It was added as an easy "tag-on" early in the development or ```ndcube``` and hasn't received much attention since.  Do we want to maintain this object and any testing it requires?

Furthermore, should we remove ```utils.wcs.reindex``` (used in the ```__init__``` of ```NDCubeOrdered```) and ```utils.wcs.add_celestial_axes``` (not used at all).  These are also carry-overs from ```sunpycube```.  They are potentially useful functions, but at this time are extraneous with ```ndcube```.  Removing them would also reduce maintenance and testing.

**Comment by Cadair** [comment]
Does it work? Do we have tests for it? I think it's useful in theory.

**Comment by DanRyanIrish** [comment]
I haven't really used it, so I'm not sure.  And I don't think we have any tests for it.  At least, not specifically for the differences between it and ```NDCube```.
But if you think it's useful, then we can write some.

**Comment by DanRyanIrish** [comment]
Decision: Leave ```NDCubeOrdered``` in and test it and the WCS functions it requires.
