### ISSUE TITLE
New get_all_coords method for NDCube

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#52]
A request for a very useful convenience function as a method on NDCube that would return the real world coords for all axes.

It could return a list of named tuples each with properties “axes” and “coords”, where “axes” was a tuple of the data axes numbers to which the coord corresponded and “coords” gave the coordinates for the whole cube as a quantity.

**Comment by Cadair** [comment]
For this to be sufficiently general you need to return an array of `(*array.shape, array.ndim)` i.e return *all* the coords for *all* the points. 

That is unless you know which dimensions are separable. i.e. for a space, space, wavelength cube you could return a 2D array for space and a 1D array for wave.

**Comment by DanRyanIrish** [comment]
Yes, that's right.  I think if the output is returned in an easy-to-follow and easy-to-access way, it'll be very useful to users.  Perhaps it can be returned as a ```namedtuple``` with the named derived from the WCS axis type names.  I've already been a little frustrated in using ```NDCube``` that's it's currently not quick and easy to pull out the coordinates of all the pixels along given axes and feel that other users, especially those not as proficient with Python and astropy, will also find so.

**Comment by DanRyanIrish** [comment]
There's information on whether there are celestial axes within the wcs.  Is that what you mean?

**Comment by Cadair** [comment]
No, the seperability isn't theoretically limited to celestial. You actually want to ask `WCS` which axes are dependant on which others.

**Comment by DanRyanIrish** [comment]
One method could be to just get all the coordinate values for all pixels along all axes.  This should return the values for all pixels for one coordinate type, e.g. longitude, as separate arrays.  Then each array could be inspected to see if the values change as you move through the array's dimensions and if they don't eliminate the dimensions along which the values are repeated.

It would be cleaner if we knew which axes were separable from the start, but I think this would get us to the result we want if we don't know that.

**Comment by Cadair** [comment]
If you are going to go brute force, then you need to return an array of the same shape as the data will *all* the coords in it. Which for large arrays will get memory and CPU intensive pretty quick

**Comment by DanRyanIrish** [comment]
Yes, I agree it's not the ideal solution.  But memory and CPU issues aside I think it should work.  But as you say, you can't always ignore memory and CPU issues.

Or we could try dropping axes and find out which ones cause ```InconsistentAxisTypesError```.  But you would think if it knows to raise that error, it must be recorded somewhere which axes are dependent...unless it's only implemented for celestial axes?

**Comment by DanRyanIrish** [comment]
I can't find anything so far about dependent axes in the ``WCS``` or ```WCSprm``` classes beyond handling celestial axes.

**Comment by DanRyanIrish** [comment]
We may need to talk directly to the ```astropy``` folks to find out.

**Comment by Cadair** [comment]
I did that, and I was show this: https://github.com/glue-viz/glue/blob/master/glue/core/coordinates.py#L258

**Comment by DanRyanIrish** [comment]
Oh wow.  What is the glue package?

**Comment by Cadair** [comment]
It's the GUI thing I was playing with at when I was sitting in your lounge :D

**Comment by DanRyanIrish** [comment]
Ha!  Oh yeh!  Sounds like that functionality should go into wcs proper.  The dependent axes bit, I mean.  I don't think we want to make a GUI a dependency for ndcube if avoidable.

**Comment by Cadair** [comment]
I would just copy the whole function into utils.wcs for now :D

**Comment by DanRyanIrish** [comment]
Ha!  Just when I'd managed to train such instincts out of me ;)

**Comment by DanRyanIrish** [comment]
This issue is tackled by PR #60.
