### ISSUE TITLE
The docstring / function signature for `NDCube.plot` is useless

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#530]
### Describe the bug

```
help(mycube.plot)
```

isn't much use because all the actual code is in `mycube.plotter.plot`, we should dynamically copy the signature and docstring.

**Comment by SolarDrew** [comment]
This may require some shenanigans - after looking into it, it turns out you can't write the `__doc__` attribute of methods. Continuing to look for a workaround.

**Comment by ayshih** [comment]
You can (usually?) write to `methodname.__func__.__doc__`, which is where `methodname.__doc__` pulls from.

**Comment by SolarDrew** [comment]
Interesting, I'll have a go at that, thanks.

**Comment by Cadair** [comment]
It would also be good to use some function signature magic (i.e. what `functools.wraps` does) to dynamically update the signature as well. I wonder if the best option for this whole thing would be a decorator on the method (can decorators access the class instance?).
