### ISSUE TITLE
Cannot update NDCollection when aligned_axes are not set

### ISSUE THREAD

**Issue by jmbhughes** [sunpy/ndcube#535]
### Describe the bug

If you are not using `aligned_axes` for an `NDCollection` and you try to `update` the collection with a new collection, you get an error. It should be possible if both `NDCollection`s are not using `aligned_axes`. 

### To Reproduce

```py
from ndcube import NDCollection, NDCube
import numpy as np
import astropy.wcs
import astropy.units as u
import astropy.wcs
import numpy as np

def generate_test_cube():
    linewidth_data = np.random.rand(4, 4) / 2 # dummy data
    linewidth_wcs = astropy.wcs.WCS(naxis=2)
    linewidth_wcs.wcs.ctype = 'HPLT-TAN', 'HPLN-TAN'
    linewidth_wcs.wcs.cunit = 'deg', 'deg'
    linewidth_wcs.wcs.cdelt = 0.5, 0.4
    linewidth_wcs.wcs.crpix = 2, 2
    linewidth_wcs.wcs.crval = 0.5, 1
    linewidth_cube = NDCube(linewidth_data, linewidth_wcs)
    return linewidth_cube

my_collection = NDCollection([("one", generate_test_cube()), ("two", generate_test_cube())])
other_collection = NDCollection([("three", generate_test_cube())])

my_collection.update(other_collection)
```
### Screenshots

<img width="905" alt="Screen Shot 2022-08-24 at 8 54 55 AM" src="https://user-images.githubusercontent.com/13068381/186451210-e84f243e-4f54-44a3-ba02-93a079e425bd.png">

### System Details

ndcube version 2.0.2

SunPy Installation Information:

General
#######
OS: Mac OS 10.16
Arch : 64bit, (i386)
SunPy : 3.0.1

Required Dependices
###################
astropy: 4.2.1
parfive: 1.3.0
numpy: 1.20.1

Optional Dependices
###################
asdf: 2.10.0
beautifulsoup4: 4.9.3
dask: 2022.2.1
drms: 0.6.2
glymur: Missing, need glymur!=0.9.0,>=0.8.18; extra == "all"
h5netcdf: Missing, need h5netcdf>=0.8.1; extra == "all"
h5py: Missing, need h5py>=3.1.0; extra == "all"
matplotlib: 3.3.4
pandas: 1.2.4
python-dateutil: 2.8.1
scikit-image: 0.18.1
scipy: 1.6.2
sqlalchemy: 1.4.36
tqdm: 4.59.0
zeep: 4.0.0

### Installation method

pip

**Comment by nabobalis** [comment]
Fixed by #535
