### ISSUE TITLE
Address reproject deprecation of "order" kwarg in NDCube.reproject_to

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#546]
### Describe the bug

The order kwarg used in `NDCube.reproject_to` has been deprecated and needs to be removed from the `ndcube` codebase.

### To Reproduce

See traceback here: https://github.com/sunpy/ndcube/runs/8189301681?check_suite_focus=true

**Comment by Cadair** [comment]
Fixed in the 2.0 branch by #564 and in main by #548.
