### ISSUE TITLE
ndcube publication: invitation for co-authors

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#590]
Dear ndcube contributors

(@Cadair @yashrsharma44 @abit2 @adwaitbhope @nabobalis @rosteen @BaptistePellorceAstro @wtbarnes @hayesla @SolarDrew @dhomeier @mateoi @dstansby @jmbhughes @byrdie @aoife-maria @ayshih @Kate028 @pllim @mwest007 @shelbej )

I'm leading a paper on the NDCube 2 API and its implementation in the ndcube package.  As ndcube contributors, I would like to invite you to be co-authors.  The overleaf document can be viewed [here](https://www.overleaf.com/read/nnhyvfgqnntb)

If you would like to be a co-author, please reply to this issue giving the following information as soon as possible:
* Name you publish under
* Affiliation
* Affiliation address
* ORCID (optional)

Feel free to send me this information privately if you prefer.  Thanks for your ndcube contributions thusfar and thanks in advance to those who agree to be co-authors.

**Comment by pllim** [comment]
I don't remember contributing to `ndcube`, maybe you can take my name off in the name of fairness. Thanks for your generosity! 😆

**Comment by hayesla** [comment]
sounds great @DanRyanIrish , glad to hear your publishing on this, and thanks for invite.

Laura A. Hayes
European Space Agency, ESTEC, Keplerlaan 1 - 2201 AZ, Noordwijk, The Netherlands, 
https://orcid.org/0000-0002-6835-2390

**Comment by Cadair** [comment]
Count me in,

Stuart Mumford
Aperio Software Ltd, Leeds, UK
0000-0003-4217-4642

**Comment by rosteen** [comment]
Great news, thanks for taking the lead on this and reaching out. My info:

Richard O’Steen
Space Telescope Science Institute, 3700 San Martin Drive, Baltimore, MD 21218, USA
https://orcid.org/0000-0002-2432-8946


From: DanRyanIrish ***@***.***>
Reply-To: sunpy/ndcube ***@***.***>
Date: Tuesday, February 14, 2023 at 5:10 AM
To: sunpy/ndcube ***@***.***>
Cc: Richard O'Steen ***@***.***>, Mention ***@***.***>
Subject: [sunpy/ndcube] ndcube publication: invitation for co-authors (Issue #590)

Provide a general description of the issue or problem.

Dear ndcube contributors

***@***.***<https://urldefense.com/v3/__https:/github.com/Cadair__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdiiuKRXY3$> @yashrsharma44<https://urldefense.com/v3/__https:/github.com/yashrsharma44__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdijAgoR6V$> @abit2<https://urldefense.com/v3/__https:/github.com/abit2__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdisCslzl0$> @adwaitbhope<https://urldefense.com/v3/__https:/github.com/adwaitbhope__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdilsbarJI$> @nabobalis<https://urldefense.com/v3/__https:/github.com/nabobalis__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdim56OoHU$> @rosteen<https://urldefense.com/v3/__https:/github.com/rosteen__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdikzAeZjw$> @BaptistePellorceAstro<https://urldefense.com/v3/__https:/github.com/BaptistePellorceAstro__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdilWNjnRL$> @wtbarnes<https://urldefense.com/v3/__https:/github.com/wtbarnes__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdit82q5I_$> @hayesla<https://urldefense.com/v3/__https:/github.com/hayesla__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdiq5fPCVR$> @SolarDrew<https://urldefense.com/v3/__https:/github.com/SolarDrew__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdip0fNJwC$> @dhomeier<https://urldefense.com/v3/__https:/github.com/dhomeier__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdilErbeug$> @mateoi<https://urldefense.com/v3/__https:/github.com/mateoi__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdiv10UTDQ$> @dstansby<https://urldefense.com/v3/__https:/github.com/dstansby__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdigPw6B64$> @jmbhughes<https://urldefense.com/v3/__https:/github.com/jmbhughes__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdipjiSnMA$> @byrdie<https://urldefense.com/v3/__https:/github.com/byrdie__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdilNgdwwe$> @aoife-maria<https://urldefense.com/v3/__https:/github.com/aoife-maria__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKditCjzqN_$> @ayshih<https://urldefense.com/v3/__https:/github.com/ayshih__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdivGjHY29$> @Kate028<https://urldefense.com/v3/__https:/github.com/Kate028__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdio9gaP_6$> @pllim<https://urldefense.com/v3/__https:/github.com/pllim__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdijjiqNl8$> @mwest007<https://urldefense.com/v3/__https:/github.com/mwest007__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdilEEiYsA$> @shelbej<https://urldefense.com/v3/__https:/github.com/shelbej__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdiv1bNlXQ$> )

I'm leading a paper on the NDCube 2 API and its implementation in the ndcube package. As ndcube contributors, I would like to invite you to be co-authors. The overleaf document can be viewed here<https://urldefense.com/v3/__https:/www.overleaf.com/read/nnhyvfgqnntb__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2t4Es5defgauP9soXpwuezEvAbmnHJD9Gnm15sZww1fMjU2UmFa8D7uh5cYiiKylCBIP4VfhUmf6DEKdijU2C2PJ$>

If you would like to be a co-author, please reply to this issue giving the following information as soon as possible:

  *   Name you publish under
  *   Affiliation
  *   Affiliation address

Thanks for your ndcube contributions thusfar and thanks in advance to those who agree to be co-authors.

**Comment by jmbhughes** [comment]
I'm happy to be a coauthor if my tiny contribution counts. 😄 

J. Marcus Hughes
Southwest Research Institute 
1050 Walnut Street, Suite 300
Boulder, CO 80302, USA
https://orcid.org/0000-0003-3410-7650

**Comment by dhomeier** [comment]
Thanks a lot; I have yet to review what I contributed, but address is

Derek Homeier
Aperio Software Ltd, Stansted, Essex, UK
https://orcid.org/0000-0002-8546-9128

**Comment by yashrsharma44** [comment]
Thanks for the mention, I would love to be a part of the co-author team 🙂 

* Name you publish under - Yash Sharma
* Affiliation - Meta Platforms Inc.
* Affiliation address - 10 Brock Street, Regents Place, London, UK

**Comment by ayshih** [comment]
Sure, I've done something non-zero. =)

Albert Y. Shih
NASA Goddard Space Flight Center
8800 Greenbelt Road, Greenbelt, MD 20771, USA
0000-0001-6874-2594

**Comment by nabobalis** [comment]
Sure:

Nabil Freij
Lockheed Martin Solar and Astrophysics Laboratory, Palo Alto, CA, USA
Bay Area Environmental Research Institute, Moffett Field, CA, USA
0000-0002-6253-082X

**Comment by SolarDrew** [comment]
I'm happy to be omitted, since I think my contribution has been pretty minimal. Thanks anyway!

**Comment by DanRyanIrish** [comment]
I have added people who have responded to this point.  Could others who would like to be co-authors please respond as soon as possible to avoid being left out :)

**Comment by abit2** [comment]
Thanks for the mention

Ankit Kumar Baruah
Workato Gmbh
WestendStrasse 28, 60325 Frankfurt/Main, Germany

**Comment by adwait-uptycs** [comment]
Glad to be a part, thanks for reaching out!

Adwait Bhope
Uptycs India Pvt. Ltd.
Aundh IT Park, Pune, MH, India - 411020
0000-0002-7133-8776

**Comment by BaptistePellorceAstro** [comment]
Hi, I am aslo happy to be included to this, Thanks again !

I think the best for me is to mention my affiliation when I worked on ndcube.
My case is a bit special, Student from France and Trainee from Norway.

Baptiste Pellorce
Claude Bernard Lyon 1 University, 43 Bd du 11 Novembre 1918, 69100 Villeurbanne
Institute of Theoretical Astrophysics, Sem Sælands vei 13, 0371 Oslo, Norvège

**Comment by dstansby** [comment]
👋 happy to be included, details below:

David Stansby
Advanced Research Computing Centre, University College London, Gower Street, London, WC1E 6BT
0000-0002-1365-1908
