### ISSUE TITLE
NDCube 2.1.0 release broke Specutils docs build

### ISSUE THREAD

**Issue by rosteen** [sunpy/ndcube#598]
### Describe the bug

Hi all,

 Since the NDCube 2.1.0 release, I have been unable to build the docs for `specutils`, running into this error (despite having the relevant NDCube class in our nitpick-exceptions file):

```
Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7f4dd674f7e0> for event 'autodoc-process-signature' threw an exception (exception: Error parsing See Also entry '* `reproject.reproject_interp`' in the docstring of reproject_to in /home/docs/checkouts/readthedocs.org/user_builds/specutils/conda/999/lib/python3.11/site-packages/ndcube/ndcube.py.)
```

You can see the full traceback at https://readthedocs.org/projects/specutils/builds/19702847/. Any ideas on how I can avoid this, or is this something that needs to be remedied on your end? Thanks.

**Comment by DanRyanIrish** [comment]
Hi @rosteen.  Thanks for this issue.  Looking through the traceback this might be an issue we missed in our testing because we always have reproject installed during testing due to our tests' dependence on sunpy.  This is despite reproject not being a required dependency.  Can you confirm whether you have `reproject` installed when you find this error?

If you don't have `reproject`, the following could be the issue.  In v2.1, the following section was added to the docstring of [`NDCubeBase.reproject_to`](https://github.com/sunpy/ndcube/blob/main/ndcube/ndcube.py#L710)
```
        See Also
        --------
        * `reproject.reproject_interp`
        * `reproject.reproject_adaptive`
        * `reproject.reproject_exact`
```
Since this is creating a link to `reproject` functions, if you don't have `reproject` installed, presumably this will break the docbuild.  Also, your traceback refers to "reproject.reproject_interp" which is consistent.

So if installing reproject fixes the problem, then the fix for v2.1.1 would be to alter the above docstring section so there aren't links to the reproject function, e.g.
```
        See Also
        --------
        The following functions in the reproject package:
        * reproject_interp
        * reproject_adaptive
        * reproject_exact
```

**Comment by Cadair** [comment]
You shouldn't need reproject installed to build the docs with links to reproject, you just need the reproject intersphinx mapping: https://github.com/sunpy/ndcube/blob/main/docs/conf.py#L92

**Comment by DanRyanIrish** [comment]
Do you mean `specutils` needs it?  Or that there must be another reasons 2.1 is breaking `specutils`'s doc build?

**Comment by Cadair** [comment]
I mean specutils needs it as they are inheriting the docstring defined in our code, so for their docs to render that docstring they need reproject's intersphinx.

Unless I am proven to be wrong I believe this is just a thing that needs changing in specutils.

**Comment by rosteen** [comment]
I still see the same error after adding the `reproject` intersphinx mapping:

```
[...]
loading intersphinx inventory from https://reproject.readthedocs.io/en/stable/objects.inv...
[...]
/Users/rosteen/opt/anaconda3/envs/specutils-dev/lib/python3.10/site-packages/numpydoc/docscrape.py:460: UserWarning: Unknown section Example in the docstring of axis_world_coords_values in /Users/rosteen/opt/anaconda3/envs/specutils-dev/lib/python3.10/site-packages/ndcube/utils/cube.py.
  warn(msg)
/Users/rosteen/opt/anaconda3/envs/specutils-dev/lib/python3.10/site-packages/numpydoc/docscrape.py:460: UserWarning: Unknown section Example in the docstring of crop in /Users/rosteen/opt/anaconda3/envs/specutils-dev/lib/python3.10/site-packages/ndcube/ndcube.py.
  warn(msg)
/Users/rosteen/opt/anaconda3/envs/specutils-dev/lib/python3.10/site-packages/numpydoc/docscrape.py:460: UserWarning: Unknown section Example in the docstring of crop_by_values in /Users/rosteen/opt/anaconda3/envs/specutils-dev/lib/python3.10/site-packages/ndcube/ndcube.py.
  warn(msg)

Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7f93435b4ee0> for event 'autodoc-process-signature' threw an exception (exception: Error parsing See Also entry '* `reproject.reproject_interp`' in the docstring of reproject_to in /Users/rosteen/opt/anaconda3/envs/specutils-dev/lib/python3.10/site-packages/ndcube/ndcube.py.)
make: *** [html] Error 2
```

**Comment by Cadair** [comment]
Well there goes that theory.

**Comment by pllim** [comment]
"Unknown section Example" is also problematic. I think it is "Examples" with the "s".

**Comment by pllim** [comment]
@rosteen , for specutils, probably easier to overwrite the inherited docstring, or stop inheriting altogether.

For ndcube though, is it fair to introduce intersphinx to optional dependency, especially if you expect this class to be inherited by a lot of downstream packages that also generate their own docstrings?

**Comment by rosteen** [comment]
Agreed, based on the `numpydocs` documentation it seems like it should be "Examples. Also looking at that documentation for See Also, I suspect maybe it's the list formatting that's messing it up? See https://numpydoc.readthedocs.io/en/latest/format.html#see-also, the format there differs from what's in the docs here.

**Comment by pllim** [comment]
ndcube, please consider failing on warnings:

https://github.com/sunpy/ndcube/blob/e477d5760c6f2e62c0b0e9fe50d6222cc323b458/.readthedocs.yml#L17

**Comment by nabobalis** [comment]
> ndcube, please consider failing on warnings:
> 
> https://github.com/sunpy/ndcube/blob/e477d5760c6f2e62c0b0e9fe50d6222cc323b458/.readthedocs.yml#L17

We do not use RTD as our CI check for docbuild fails within sunpy broadly.

We have a dedicated Actions build that should fail on warnings that uses `-W` to raise all warnings as errors. 

Why this error is not seen within the ndcube doc build needs to be worked out.

**Comment by pllim** [comment]
Can ndcube do a quick bugfix release so specutils can build docs again? Thanks!

**Comment by nabobalis** [comment]
https://github.com/sunpy/ndcube/releases/tag/v2.1.1 was tagged, that is out on pypi. So in theory should be fixed for specutils.

**Comment by pllim** [comment]
Thanks!
