### ISSUE TITLE
Fix the RTD build

### ISSUE THREAD

**Issue by Cadair** [sunpy/ndcube#62]

**Comment by nabobalis** [comment]
What's the issue?

**Comment by DanRyanIrish** [comment]
I defer to @Cadair on this one.

**Comment by Cadair** [comment]
Done: https://readthedocs.org/projects/ndcube/builds/6780180/

**Comment by DanRyanIrish** [comment]
Yay!!!!!

**Comment by DanRyanIrish** [comment]
This issue is fixed by PR #65
