### ISSUE TITLE
Method to extract sub-NDCube using physical coords

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/ndcube#7]
A method enabling the user to define a region of interest based on a range of physical units.
* The ranges should be input as ```astropy Quantities``` with units consistent with the WCS axes.
* The ranges should be entered in order of the ```NDCube``` axes.
* ```NDCube.world_to_pixel``` can then be used to determine the upper and lower limits in pixel coordinates and then slice the ```NDCube``` accordingly.
* If the physical coordinates correspond to non-integer pixel values, they should be rounded up or down to the nearest integer.

**Comment by Cadair** [comment]
This should follow the new API of map submap. In that you specify one corner and widths.

**Comment by DanRyanIrish** [comment]
Is that API in master yet?  From what I see it's still defined by bottom left and top right...

And what's the benefit of this API over defining a minimum and maximum for each axis separately?

**Comment by Cadair** [comment]
Yeah it's in 0.8. The advantage is that it works irrelevant of orientation or coordinate frame.

**Comment by DanRyanIrish** [comment]
Hmmm.  How many widths do you specify?  If you just specify two then it's still the same as identifying a top right corner, isn't it?

**Comment by DanRyanIrish** [comment]
Resolved by inclusion of NDCube.crop_by_coords.
