### ISSUE TITLE
Stable docs page shows dev version instead of stable release version

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/ndcube#728]
The "stable" docs page shows the (very old) dev version rather than the actual version number at the top left of the page. See below.

<img width="476" alt="image" src="https://github.com/sunpy/ndcube/assets/8676141/44b2f030-80a7-4d0c-9c91-578c8f1c90e0">

**Comment by nabobalis** [comment]
https://readthedocs.org/projects/ndcube/builds/24721563/ is building.
